version: 2.1
orbs:
  cfa: continuousauth/npm@1.0.2
jobs:
  test:
    docker:
      - image: cimg/node:16.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: echo "export MY_SECRET=foobar" >> $BASH_ENV
      - run: echo "This is $MY_SECRET"

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release
